### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/june-28#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by alueib** [comment]
Hi there!

**Comment by Sbruk** [comment]
Hello Github!

**Comment by APBEI** [comment]
Hello

**Comment by rrujoiu** [comment]
please invite me to this repository

**Comment by ImSo06** [comment]
o/

**Comment by kesslerb** [comment]
Hello World!

**Comment by zkelemen** [comment]
Test comment: hello!

**Comment by djciaro** [comment]
Morning

**Comment by mayaydineib** [comment]
Hello could you please invite me to the repository

**Comment by spartan05** [comment]
Hello there!

**Comment by jdar002** [comment]
This is my first comment in GitHub

**Comment by boggiedan** [comment]
Hi there

**Comment by PoloEIB** [comment]
hi
